version: 2
updates:
  - package-ecosystem: gradle
    directory: /greater-art
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      android-gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /useless-calculator
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      calculator-gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
